{ lib, ... }:
{
  flake.commonModules.dns =
    { config, pkgs, ... }:
    let
      inherit (lib.lists) map singleton;
      inherit (lib.strings) substring;

      id = "7f2bf8";
      idv6 = "${substring 0 2 id}:${substring 2 4 id}";

      mkNextDnsServer =
        { ip, hostName }:
        {
          inherit ip;
          trust_negative_responses = true;
          connections = [
            {
              protocol = {
                type = "h3";
                server_name = "dns.nextdns.io";
                path = "/${id}/${hostName}";
              };
            }
            {
              protocol = {
                type = "quic";
                server_name = "${hostName}-${id}.dns.nextdns.io";
              };
            }
            {
              protocol = {
                type = "https";
                server_name = "dns.nextdns.io";
                path = "/${id}/${hostName}";
              };
            }
            {
              protocol = {
                type = "tls";
                server_name = "${hostName}-${id}.dns.nextdns.io";
              };
            }
          ];
        };
    in
    {
      services.hickory-dns = {
        enable = true;

        package = pkgs.hickory-dns.overrideAttrs (old: {
          cargoBuildFeatures = (old.cargoBuildFeatures or [ ]) ++ [
            "tls-aws-lc-rs"
            "https-aws-lc-rs"
            "quic-aws-lc-rs"
            "h3-aws-lc-rs"
          ];

          meta.mainProgram = "hickory-dns"; # upstream does not seem to believe in mainProgram
          meta.platforms = old.meta.platforms ++ lib.platforms.darwin;
        });

        settings = {
          listen_port = 53;
          listen_addrs_ipv6 = singleton "::";

          zones = singleton {
            zone = ".";
            zone_type = "External";

            stores.type = "forward";
            stores.name_servers =
              [
                # { # FIXME: Slow.
                #   inherit (config.networking) hostName;
                #   ip = "2a07:a8c0::${idv6}";
                # }
                # {
                #   inherit (config.networking) hostName;
                #   ip = "2a07:a8c1::${idv6}";
                # }
                {
                  inherit (config.networking) hostName;
                  ip = "45.90.28.0";
                }
                {
                  inherit (config.networking) hostName;
                  ip = "45.90.30.0";
                }
              ]
              |> map mkNextDnsServer;
          };
        };
      };
    };

  flake.darwinModules.dns =
    { lib, ... }:
    let
      inherit (lib.lists) singleton;
    in
    {
      networking.dns = singleton "::1";
    };

  flake.nixosModules.dns = {
    services.resolved.enable = false;
    networking.resolvconf.enable = false;

    environment.etc."resolv.conf".text = /* resolvconf */ ''
      # Generated by NixOS modules, should use the Hickory-DNS forwarder.
      options edns0 trust-ad
      nameserver ::1
    '';
  };
}
