{ self, lib, ... }:
let
  inherit (lib.attrsets) attrValues filterAttrs mapAttrs;
in
{
  # TODO: This entire file shouldn't exist, it's like the old packages.mod.nix.
  flake.people = {
    self = self.people.rgbcube;

    rgbcube = {
      name = "RGBCube";
      email = "git@rgbcu.be";
      admin = true;
      ssh.key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBVkWUQ6Z4OK539tore/R5wnueNPPaX532RUAld8UOCo rgbcube";

      # One per YubiKey, generated by:
      #
      # pamu2fcfg --nouser --pin-verification --no-user-presence --type eddsa --origin pam://self
      fido2-credentials = [
        # Main
        "8ugPbT/mgBgV91adGcJwFr5xuIrZ3h39cUU2nojY6aMCMC5InJJUVyx9O8X0j8ZuWcy12GVvdCn0jnNUHxDvSAsZt4yb/UG5ecX8t0DXy4+Y+1raSs99UQL3iPGqoseIJtDly+iqQatlfrA9u9i6OU1FY2lJL87Z/Y0vtcSN0qw=,m6vgzxFV5IttduNwaQN51SYkxWeQyMQBvO0gUZAalUE=,eddsa,+pin"
      ];
    };
  };

  flake.machines = {
    # OLD INFRASTRUCTURE
    best.ssh = {
      enable = true;
      hostName = "rgbcu.be";
      key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBUsMV591/9VqzjBiMqdxJId0C7PlZTIXQByHEILWMwc the@best";
    };
    disk.ssh = {
      enable = true;
      hostName = "mail1.rgbcu.be";
      key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIItpYQ3Pz6zFifKXvFX7xAC8aby9RW/m5PkW8T9SOee4 floppy@disk";
    };

    # TYLER
    lyrae.ssh = {
      enable = true;
      user = "nix-ssh";
      hostName = "typing.ink";
      key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBgIcUZYHyzcg4YSL6DWsqhRDnjri35KPOpF6V42wlvq lyrae";
    };
  };

  flake.ssh-keys =
    mapAttrs (_: { ssh, ... }: ssh.key) <| removeAttrs self.people [ "self" ] // self.machines;

  flake.ssh-keys-admin =
    removeAttrs self.people [ "self" ]
    |> filterAttrs (
      _:
      {
        admin ? false,
        ...
      }:
      admin
    )
    |> attrValues
    |> map ({ ssh, ... }: ssh.key);
}
