{ self, lib, ... }:
let
  inherit (lib.attrsets) attrValues filterAttrs mapAttrs;
in
{
  flake.people = {
    self = self.people.rgbcube;

    rgbcube = {
      name = "RGBCube";
      email = "git@rgbcu.be";
      admin = true;
      ssh-key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBVkWUQ6Z4OK539tore/R5wnueNPPaX532RUAld8UOCo rgbcube";

      # One per YubiKey, generated by:
      #
      # pamu2fcfg --nouser --pin-verification --no-user-presence --type eddsa --origin pam://self
      fido2-credentials = [
        # Main
        "8ugPbT/mgBgV91adGcJwFr5xuIrZ3h39cUU2nojY6aMCMC5InJJUVyx9O8X0j8ZuWcy12GVvdCn0jnNUHxDvSAsZt4yb/UG5ecX8t0DXy4+Y+1raSs99UQL3iPGqoseIJtDly+iqQatlfrA9u9i6OU1FY2lJL87Z/Y0vtcSN0qw=,m6vgzxFV5IttduNwaQN51SYkxWeQyMQBvO0gUZAalUE=,eddsa,+pin"
      ];
    };
  };

  flake.machines = {
    istanbul.ssh-key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMCykEkiotbnje7b7Gg7f+fg58zOxRjNKuJO0z1eVrmF istanbul";
    vienna.ssh-key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIO89LpzcmPit5ZanIpRhevqoUWpeB9Ja/sLxyKivfjJ vienna";

    pala.ssh-key = self.people.self.ssh-key;

    # OLD INFRASTRUCTURE
    best.ssh-key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBUsMV591/9VqzjBiMqdxJId0C7PlZTIXQByHEILWMwc the@best";
    disk.ssh-key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIItpYQ3Pz6zFifKXvFX7xAC8aby9RW/m5PkW8T9SOee4 floppy@disk";
    nine.ssh-key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILJDqnItmvXZMTSwzbalr+9jzS4kSJm5PWEpI8GOpebF seven@nine";
  };

  flake.ssh-keys = mapAttrs (_: { ssh-key, ... }: ssh-key) (
    removeAttrs self.people [ "self" ] // self.machines
  );

  flake.ssh-keys-admin =
    removeAttrs self.people [ "self" ]
    |> filterAttrs (
      _:
      {
        admin ? false,
        ...
      }:
      admin
    )
    |> attrValues
    |> map ({ ssh-key, ... }: ssh-key);
}
