{ lib, self, ... }:
{
  flake.commonModules.resolver =
    { config, pkgs, ... }:
    let
      inherit (lib.fixedPoints) fix;
      inherit (lib.lists)
        elem
        map
        optional
        singleton
        subtractLists
        unique
        ;
      inherit (lib.strings) substring;

      id = "7f2bf8";
      idv6 = "${substring 0 2 id}:${substring 2 4 id}";

      mkNextDnsServer =
        { ip, hostName }:
        {
          inherit ip;
          trust_negative_responses = true;
          connections = [
            {
              protocol = {
                type = "h3";
                server_name = "dns.nextdns.io";
                path = "/${id}/${hostName}";
              };
            }
            {
              protocol = {
                type = "quic";
                server_name = "${hostName}-${id}.dns.nextdns.io";
              };
            }
            {
              protocol = {
                type = "https";
                server_name = "dns.nextdns.io";
                path = "/${id}/${hostName}";
              };
            }
            {
              protocol = {
                type = "tls";
                server_name = "${hostName}-${id}.dns.nextdns.io";
              };
            }
          ];
        };
    in
    {
      system.services.resolver = {
        imports = singleton self.modularServices.hickory-dns;

        hickory-dns = {
          package = pkgs.hickory-dns.overrideAttrs (
            old:
            let
              oldBuildFeatures = old.cargoBuildFeatures or (old.buildFeatures or [ ]);
              oldCheckFeatures = old.cargoCheckFeatures or (old.checkFeatures or oldBuildFeatures);

              replaceRingFeatures =
                features:
                (
                  features
                  |> subtractLists [
                    "dnssec-ring"
                    "h3-ring"
                    "https-ring"
                    "quic-ring"
                    "tls-ring"
                  ]
                )
                ++ optional (elem "dnssec-ring" features) "dnssec-aws-lc-rs"
                ++ [
                  "h3-aws-lc-rs"
                  "https-aws-lc-rs"
                  "quic-aws-lc-rs"
                  "tls-aws-lc-rs"
                ]
                |> unique;

            in
            fix (final: {
              buildFeatures = final.cargoBuildFeatures;
              checkFeatures = final.cargoCheckFeatures;
              cargoBuildFeatures = replaceRingFeatures oldBuildFeatures;
              cargoCheckFeatures = replaceRingFeatures oldCheckFeatures;

              env = (old.env or { }) // {
                AWS_LC_SYS_CMAKE_BUILDER = 1;
                LIBSQLITE3_SYS_USE_PKG_CONFIG = 1;
              };

              buildInputs = (old.buildInputs or [ ]) ++ singleton pkgs.sqlite;

              nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [
                pkgs.cmake
                pkgs.pkg-config
              ];

              meta.mainProgram = "hickory-dns"; # upstream does not seem to believe in mainProgram
              meta.platforms = old.meta.platforms ++ lib.platforms.darwin;
            })
          );

          tomlFormat = pkgs.formats.toml { };

          settings = {
            listen_port = 53;
            listen_addrs_ipv6 = singleton "::";

            zones = singleton {
              zone = ".";
              zone_type = "External";

              stores.type = "forward";
              stores.name_servers =
                [
                  # { # FIXME: Slow.
                  #   inherit (config.networking) hostName;
                  #   ip = "2a07:a8c0::${idv6}";
                  # }
                  # {
                  #   inherit (config.networking) hostName;
                  #   ip = "2a07:a8c1::${idv6}";
                  # }
                  {
                    inherit (config.networking) hostName;
                    ip = "45.90.28.0";
                  }
                  {
                    inherit (config.networking) hostName;
                    ip = "45.90.30.0";
                  }
                ]
                |> map mkNextDnsServer;
            };
          };
        };
      };
    };

  flake.darwinModules.resolver =
    { lib, ... }:
    let
      inherit (lib.lists) singleton;
    in
    {
      networking.dns = singleton "::1";
    };

  flake.nixosModules.resolver = {
    services.resolved.enable = false;
    networking.resolvconf.enable = false;

    environment.etc."resolv.conf".text = /* resolvconf */ ''
      # Generated by NixOS modules, should use the Hickory resolver.
      options edns0 trust-ad
      nameserver ::1
    '';
  };
}
